title: Flexr Grid
description: Flexr is a CSS responsive grid framework for modern browsers.
email: dmblakedesign@gmail.com
copyright: !!html 2016&ndash;2018 Daniel Blake
author: Daniel Blake

baseurl: ""
url: https://flexrgrid.com

sass:
    style: compressed

compress_html:
   clippings: all
   comments: ["<!--","-->"]
   ignore:
      envs: []

include:
   - _pages
   - .htaccess

exclude:
   - .sass-cache
   - .gitignore
   - .jekyll-metadata
   - channel.yml
   - node_modules
   - src
   - yarn.lock
   - package.json
   - gulpfile.js
   - README.md
   - CNAME
   - flexrgrid.csr
   - flexrgrid.key


defaults:
   -
      scope:
         path: "_pages"
      values:
         layout: "page"
