title: Flexr Grid
description: Flexr is a css responsive grid framework for modern browsers.
email: dmblakedesign@gmail.com

baseurl: ""
url: http://flexrgrid.com

sass:
    style: compressed

creator: Daniel Blake

include:
   - _pages
   - .htaccess

exclude:
   - .jekyll-metadata

#Defaults
defaults:
   -
      scope:
         path: "_pages"
      values:
         layout: "base"
