title: Flexr Grid
description: Flexr is a CSS responsive grid framework for modern browsers.
email: dmblakedesign@gmail.com
copyright: 2016–2017 Daniel Blake
author: Daniel Blake

baseurl: ""
url: http://flexrgrid.com

sass:
    style: compressed

include:
   - _pages
   - .htaccess

exclude:
   - .sass-cache
   - .jekyll-metadata
   - node_modules
   - js
   - yarn.lock
   - package.json
   - gulpfile.js


defaults:
   -
      scope:
         path: "_pages"
      values:
         layout: "page"
